services:
  backend:
    build:
      context: ./frotto-server-main
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.frotto-api.rule=Host(`api.frotto.com.br`)"
    - "traefik.http.routers.frotto-api.entrypoints=http,https"
    - "traefik.http.routers.frotto-api.tls=true"
    - "traefik.http.services.frotto-api.loadbalancer.server.port=5000"



  frontend:
    build:
      context: ./frotto-ui-main
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frotto-web.rule=Host(`frotto.com.br`,`www.frotto.com.br`)"
      - "traefik.http.routers.frotto-web.entrypoints=http,https"
      - "traefik.http.routers.frotto-web.tls=true"
      - "traefik.http.services.frotto-web.loadbalancer.server.port=80"

