services:
  backend:
    build:
      context: ./frotto-server-main
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped

  frontend:
    build:
      context: ./frotto-ui-main
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped
